Categories:
  - System
License: MIT
AuthorName: Robotmind
AutoName: Luncher
SourceCode: https://github.com/nez/luncher
IssueTracker: https://github.com/nez/luncher/issues
RepoType: git
Repo: https://github.com/nez/luncher.git
Builds:
  - versionName: 1.0.0
    versionCode: 1
    commit: 3fed5702764af8ea5ddcc9a04b340b44cccb26a0
    rm: WIP.md
    output: android/app/build/outputs/apk/release/app-release-unsigned.apk
    sudo:
      - apt-get update
      - apt-get install -y nodejs npm
    prebuild:
      - npm ci
      - npx expo prebuild --platform android --clean --no-install
      - sed -i '/signingConfig /d' android/app/build.gradle
    build:
      - cd android
      - gradle assembleRelease
